variables:
  # The GIT_DEPTH option makes the project clone process in each job a bit faster, pulling only the current commit, not the whole Git history.
  GIT_DEPTH: "1"
  # overlay2 filesystem for the Docker build, which is faster and less space consuming
  DOCKER_DRIVER: overlay2
  # Abilita debug gitlab-ci
  #CI_DEBUG_TRACE: "true"

stages:
  - build
  - test
  - package
  - push
  - cve:scan

.base-build:
  image: gradle:7.2.0-jdk16-openj9
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
  cache:
    key: "$CI_COMMIT_REF_SLUG-gradle-cache"
    paths:
      - .gradle/

# BUILD
app-build:
  extends: .base-build
  stage: build
  script:
    - gradle assemble

# TEST
app-test:
  extends: .base-build
  stage: test
  script:
    - gradle check
  artifacts:
    paths:
      - app/build/reports/jacoco/test/jacocoTestReport.xml
    expire_in: 1 day

# PACKAGE
app-package:
  extends: .base-build
  stage: package
  script:
    - gradle jar
  artifacts:
    paths:
      - app/build/libs/app.jar
    expire_in: 1 day
